%Draw Colorbar
function handle = colorbar(cbin, rbin, ystring, pos);

cpos = get(gca, 'Position');
units = get(gca, 'Units');

colrect = [cpos(1)+cpos(3)*1.02 cpos(2) cpos(3)*0.03 cpos(4)];
d = axes('Units', units, 'Position', colrect, ...
    'TickDir', 'in', ...
    'TickLength', [0.01 0], ... 
    'Fontsize', 8, ...
    'Visible', 'on', ...
    'YAxisLocation', 'right', ...
    'Ylim', [min(rbin) ceil(max(rbin))], 'Ytick', rbin, ...
    'YScale', 'log', 'YTickLabel', cellstr(num2str(rbin', '%0.2f')),...
    'Xlim', [1 2], 'XTickLabel', [],...
    'Color', 'none', ...
    'Box', 'on', 'Layer', 'bottom');
set(gca, 'NextPlot', 'add');
[C2 h4] = contourf([1 2], rbin, [log10(rbin+eps)' log10(rbin+eps)'], log10(cbin));
set(h4, 'EdgeColor', 'none');
ylabel(ystring);


